name: cms-frontend-node-javascript-ssr

services:
  app:
    container_name: cms-frontend-node-javascript-ssr
    build: .
    ports:
      - "4000:4000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      PORT: "4000"
      API_BASE_URL: "${API_BASE_URL:-http://host.docker.internal:3000}"
